### ISSUE TITLE
Plugin expects a english locale

### ISSUE THREAD

**Issue by chrisbra** [ZeroKnight/vim-signjump#3]
Hi,
this plugin parses the output of the `:sign` command. However it only works, if it is run in an english locale (e.g. try running `:lang mes de_DE` and it will fail miserably :()
So please consider for parsing switching the locale to english. I am doing something similar for my [DynamicsSign](https://github.com/chrisbra/DynamicSigns) plugin [here](https://github.com/chrisbra/DynamicSigns/blob/master/autoload/DynamicSigns.vim#L232-L247)

**Comment by ZeroKnight** [comment]
Thanks for the report! I'll have a fix for this a bit later. Thanks for the sample too, that will definitely help... and by that I mean I wouldn't have known what to do otherwise ;)

**Comment by ZeroKnight** [comment]
Hi @chrisbra, could you confirm that the latest commit fixes the issue on your end?

**Comment by chrisbra** [comment]
Unfortunately, it doesn't, because the locale is called `C` and not `'C'`

Here is a patch:
```patch
diff --git a/autoload/signjump.vim b/autoload/signjump.vim
index 6489095..13d0700 100644
--- a/autoload/signjump.vim
+++ b/autoload/signjump.vim
@@ -13,7 +13,7 @@ function! signjump#get_buffer_signs(buffer) abort
   " Ensure :sign place can be parsed in all locales
   let l:lang_save = v:lang
   if v:lang !=# 'C'
-    silent! language messages 'C'
+    silent! language messages C
   endif
```

Note, I think it is good style to also remove the `!` attribute to the `silent` modifier.

**Comment by ZeroKnight** [comment]
D'oh! Blind habits got the better of me on this one. Thanks.

@chrisbra Fixed. That should hopefully do it.
